### ISSUE TITLE
Game crashes if you exit game when dead.

### ISSUE THREAD

**Issue by manas96** [MovingBlocks/DestinationSol#255]
### What you were trying to do
I was trying to exit the game after I had died.
### What actually happened
Game crashed (NullPointerException). 
### How to reproduce

* Step 1 Start game. You might want to select Small Imperial ship and drop all items to do Step 2 faster.
* Step 2 Die!
* Step 3 Press ESC and 'Exit' button. 

### Log details
Full stacktrace:
ERROR [LWJGL Application] (SolApplication.java:123) - Fatal Error:
java.lang.NullPointerException
	at org.destinationsol.game.SaveManager.writeMercs(SaveManager.java:92)
	at org.destinationsol.game.SaveManager.writeShip(SaveManager.java:51)
	at org.destinationsol.game.SolGame.saveShip(SolGame.java:306)
	at org.destinationsol.game.SolGame.onGameEnd(SolGame.java:268)
	at org.destinationsol.SolApplication.finishGame(SolApplication.java:218)
	at org.destinationsol.game.screens.MenuScreen.updateCustom(MenuScreen.java:87)
	at org.destinationsol.ui.SolInputManager.update(SolInputManager.java:222)
	at org.destinationsol.SolApplication.update(SolApplication.java:143)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:121)
	at org.destinationsol.SolApplication.render(SolApplication.java:102)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by manas96** [comment]
Working on this. Even if you had hired mercenaries at the time of death, the same exception is produced by the SaveManager.writeMercs() method.

**Comment by manas96** [comment]
Oh! Seems this was fixed in #246 merge. I didn't have my local repo updated with the latest commits. Sorry!

**Comment by vampcat** [comment]
In that case, I'll close the issue :)
