### ISSUE TITLE
Game Won't Start on Linux Mint 17.1 64-bit

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#40]
Reported in Steam and chat via IRC: http://steamcommunity.com/app/342980/discussions/0/523890681410169922/

The user is using Linux Mint 17.1 64-bit and it was working in version 1.0.2. It looks like libGDX isn't returning any valid resolutions, hence the array out of bounds exception.

This is the exception that is thrown.
Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:446)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:118)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)

**Comment by SimonC4** [comment]
Turns out this isn't to do with the resolution changes. It's caused by a bug in lwjgl when the user has multiple graphics cards on linux https://github.com/LWJGL/lwjgl/issues/112

libGDX is using version 2.9.2 of lwjgl, which has the bug. It has since been fixed and I got the user to try the test fix, which is this file https://github.com/tfg13/lwjgl/releases/tag/test_lwjgl%23112

lwjgl 2 is no longer supported and it looks like libGDX is moving to lwjgl 3 http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19761&p=82922&hilit=lwjgl#p82922. Not sure what the timeframe is for this.

I'm going to leave this issue open as I think we should make sure the fix rolls in to steam and the build process. As the lib files are automatically grabbed during the build process, it might need to be a manual process until libGDX uses the new version of lwjgl.

**Comment by Cervator** [comment]
Related log provided by Froward - MC running on the same system, hitting the same issue

http://pastebin.com/eZqKT01T

If anything we could harden the code a bit to see if there are no "supported" resolutions and in that case exit more gracefully

**Comment by Cervator** [comment]
Added information on Steam now: http://steamcommunity.com/app/342980/discussions/1/530646715631614999/

Although that may be an indirect issue from the workaround then causing issues with audio drivers for that user?

**Comment by SimonC4** [comment]
Interesting that the audio is throwing up an issue too. I'm fairly certain that if there's no audio it is not a showstopper as the game carries on. I could reproduce this in my linux VM by disabling the audio. It's the next line which causes the game to not start.

Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys

Some theories:
1. The audio issue is the cause of the problem and there may be nothing we can do. I see that other Java games on steam state a requirement of OpenAL compatible sound cards. Maybe we should state that too.
2. The JRE on linux isn't working on this users machine. The user tried running with local java, but I don't think the fix had been used in that instance, based on the error message.

**Comment by grauerkoala** [comment]
Okay, I've experimented some more. 

First off, to answer the questions you posted over at the Steam discussion:
> So just to be sure what you're doing, you've replaced the LWJGL file with the workaround, but that then triggers an issue with an audio library file?
In fact, as I have now noticed, the outputs are exactly the same with the workaround library as without it. So the workaround isn't the thing that triggers the audio issue. This also leads me to suspect that I may not even need to use the workaround at all even though my notebook contains two graphics cards (or I simply haven't made it to that problem yet).

> What version of linux are you using?
Debian Jessie. My two graphics cards are being handled by Bumblebee.

> I'm fairly certain that in the bottom output you posted the cause of this issue is the two graphics cards. Could try the fix in the original post and try running with your local java again and posting the output.
Both outputs were produced with the fix in place. However, as mentioned above, replacing the fixed library with the original didn't change anything about the output.

> You could also try opening a terminal and running sol64.sh from the Steam folder. This launches the game with the 64-bit java.
The output from using sol64.sh is exactly the same as the output I get when I use my local Java.


Moving on to the discussion here on GitHub:
> Interesting that the audio is throwing up an issue too. 
This only happened with the 32 bit Java. I'm embarrassingly ignorant regarding the workings of audio on Linux systems, but here's what I'm assuming: since my system is a 64 bit one and I tried to run a 32 bit Java on it, the audio library tried to use syscalls on a binary that it needed to be 32 bit but which was actually 64 bit. Or something. As far as I understand it, Steam provides a 32 bit Ubuntu-like environment for the games which works well with my audio setup (on my notebook), so it's actually possible that Steam calls the 32 bit Java binary via sol.sh and it moves on to an error other than the audio one. No idea how to verify this since Steam isn't exactly forthcomming regarding the output of error messages even on its console.

Interestingly enough, a way back I've managed to bust the sound setup (software) on my desktop Linux, but the game runs perfectly fine.

**Comment by grauerkoala** [comment]
Turns out, it's probably a similar issue as above. Instead of failing to find the correct resolution like in the issue referenced above, my problem is caused by the fact that I usually have an external monitor connected to my notebook and the notebook screen turned off. It would appear that LWJGL is not able to parse the xrandr output in such a manner that they can detect this, causing the ArrayIndexOutOfBoundsException.
When I instead only keep my notebooks screen active and the external one disabled, everything works out fine.

Which means it's not an issue with Destination Sol in particular but rather with said library. I'm heading over there now to let them know.

**Comment by erazor83** [comment]
Maybe it helps someone else.

I got the same issue with a different game.

For me (Gentoo) it helped to install the xrandr tool. I got the libxrandr already but only after installing the tool the error was gone.
