### ISSUE TITLE
Game Fails to Start After Upgrading from v1.4.1 to v2.0.0

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#474]
### What you were trying to do
Run the game after upgrading from version 1.4.1 (the current Steam version) to version 2.0.0.

### What actually happened
The game crashed after the splash screen.

### How to reproduce
The controlType values have changed in settings.ini from numbers in v1.4.1 to an enum in v2.0.0. Upgrading from v1.4.1 to v2.0.0 is the proper way to reproduce this issue, however the following steps allow you to reproduce this issue

* Step 1 - In the settings.ini file, change the value of _controlType_ to _1_
* Step 2 - Run the game

### Log details and game version
Version 2.0.0

```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant org.destinationsol.GameOptions.ControlType.1
	at java.base/java.lang.Enum.valueOf(Enum.java:266)
	at org.destinationsol.GameOptions$ControlType.valueOf(GameOptions.java:26)
	at org.destinationsol.GameOptions.<init>(GameOptions.java:188)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:109)
```

### Computer details
N/A

**Comment by NicholasBatesNZ** [comment]
Fixed by #482
