### ISSUE TITLE
Game Crashes When Resuming Previous Game After Upgrade from v1.4

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#486]
### What you were trying to do
Resume the previous game after upgrading from version 1.4.1 (the current Steam version) to version 2.0.0.

### What actually happened
The game crashed after choosing "continue"

### How to reproduce
The hull values have changed in prevShip.ini between v1.4.1 and v2.0.0. Upgrading from v1.4.1 to v2.0.0 is the proper way to reproduce this issue, however the following steps allow you to reproduce this issue

Step 1 - In the prevShip.ini file, change the value of hull to imperialSmall instead of core:imperialSmall
Step 2 - Run the game and choose Play Game and then Continue.

### Log details and game version

```
java.lang.RuntimeException: Invalid resource name (missing namespace?) `imperialSmall`
	at org.destinationsol.assets.Assets.parsePath(Assets.java:69)
	at org.destinationsol.assets.Assets.getJson(Assets.java:156)
	at org.destinationsol.assets.json.Validator.getValidatedJSON(Validator.java:34)
	at org.destinationsol.files.HullConfigManager.read(HullConfigManager.java:115)
	at org.destinationsol.files.HullConfigManager.getConfig(HullConfigManager.java:96)
	at org.destinationsol.game.SaveManager.readShip(SaveManager.java:209)
	at org.destinationsol.game.SolGame.readShipFromConfigOrLoadFromSaveIfNull(SolGame.java:238)
	at org.destinationsol.game.SolGame.createGame(SolGame.java:221)
	at org.destinationsol.game.SolGame.<init>(SolGame.java:198)
	at org.destinationsol.SolApplication.play(SolApplication.java:255)
	at org.destinationsol.menu.LoadingScreen.updateCustom(LoadingScreen.java:47)
	at org.destinationsol.ui.SolInputManager.update(SolInputManager.java:238)
	at org.destinationsol.SolApplication.update(SolApplication.java:204)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:182)
	at org.destinationsol.SolApplication.render(SolApplication.java:146)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:149)
```

### Computer details
N/A

**Comment by SimonC4** [comment]
A similar issue exists with the items values in prevShip.ini. There's also another issue with no x and y coordinates in the file, which causes the ship to start in the middle of sun and near instance death. I won't create those as separate issues as depending on the solution we may just make it that you're unable to continue a previous game.

**Comment by NicholasBatesNZ** [comment]
[This](https://github.com/MovingBlocks/gestalt/wiki/Gestalt-Asset-Core-Quick-Start#contextual-asset-resolution) is probably the solution for the assets.
