### ISSUE TITLE
Game Crashes Using Controller

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#487]
### What you were trying to do
Start a game using the controller.

### What actually happened
Game crashed to desktop

### How to reproduce
* Version 2.0.0
* Change the input method to controller. It doesn't matter if a controller is connected or not.
* Click "Play Game" and either continue or choose a new game.
* Game crashes to desktop

### Log details and game version
```
com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.lwjgl3.Lwjgl3ControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:113)
	at com.badlogic.gdx.controllers.Controllers.clearListeners(Controllers.java:67)
	at org.destinationsol.menu.InputMapControllerScreen.onAdd(InputMapControllerScreen.java:206)
	at org.destinationsol.ui.SolInputManager.addScreen(SolInputManager.java:164)
	at org.destinationsol.menu.InputMapScreen.onAdd(InputMapScreen.java:298)
	at org.destinationsol.ui.SolInputManager.addScreen(SolInputManager.java:164)
	at org.destinationsol.ui.SolInputManager.setScreen(SolInputManager.java:159)
	at org.destinationsol.menu.OptionsScreen.updateCustom(OptionsScreen.java:108)
	at org.destinationsol.ui.SolInputManager.update(SolInputManager.java:238)
	at org.destinationsol.SolApplication.update(SolApplication.java:204)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:182)
	at org.destinationsol.SolApplication.render(SolApplication.java:146)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:149)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Class not found: com.badlogic.gdx.controllers.lwjgl3.Lwjgl3ControllerManager
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:30)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:110)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.controllers.lwjgl3.Lwjgl3ControllerManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:28)
	... 16 more
```

### Computer details
Windows 10

**Comment by BenjaminAmos** [comment]
This was due to an oversight on my part when I converted the code to use LWJGL3 (in #360). There is an incorrect dependency in the desktop facade for the LibGDX controller back-end. The original LWJGL2 code used the `gdx-controllers-desktop` library (which used lwjgl internally, as can be seen [here](https://github.com/libgdx/libgdx/blob/8e71c8e24d81c73e704a353743b3913522ad0464/extensions/gdx-controllers/gdx-controllers-desktop/build.gradle#L20)), however the LWJGL3 back-end requires the `gdx-controllers-lwjgl3` library instead. There is no equivalent library for `gdx-controllers-platform`, however I removed it with no apparent side-effects.

I may submit a pull request for this but for now, there is a simple fix:
- Change line 31 of `desktop/build.gradle` to:
```groovy
compile "com.badlogicgames.gdx:gdx-controllers-lwjgl3:$gdxVersion"
```
- Remove the following line (line 32):
```groovy
compile "com.badlogicgames.gdx:gdx-controllers-lwjgl3-platform:$gdxVersion-natives-desktop"
````
