### ISSUE TITLE
Game crashes when opening a menu while entering a portal

### ISSUE THREAD

**Issue by IsaacLic** [MovingBlocks/DestinationSol#498]
When the player opens a menu exactly when they enter a teleporter, the game crashes with the message "Something is trying to get a SolShip hero while the hero is in Transcendent state." 

### How to reproduce

As you enter the portal, repeatedly press the key to open the item or mercenary menu. If you open the menu exactly as the hero becomes transcendent, it will crash the game. This may take several tries to accomplish.

**Comment by Avalancs** [comment]
Which branch did you play the game on? Or if you didn't download the game, was it fro, steam, or the android store?

I tested this on the newest develop branch, and while traveling through a teleporter the items and mercenaries tab is greyed out, and the hotkeys also do not open them, so the error does not trigger.

**Comment by IsaacLic** [comment]
I tested it on the most recent develop branch. If a person tries to open a menu exactly as they enter the portal, then the error can happen. If the menu is opened right before, then it opens properly, and once the portal has been entered, the menu can't be opened. This is a specific race condition that can only happen if the menu command is able to start, but the hero becomes transcendent before the menu can actually be opened.

It doesn't happen every time. It took me ~10 tries to reproduce it, but it does happen.

**Comment by DJPlaya** [comment]
+1

**Comment by BenjaminAmos** [comment]
A more reliable way I've found to reproduce is to hold-down the `I` key (for opening the inventory) before entering the star port and then releasing it just after entering it.

Also, this is the stacktrace.
```stacktrace
Exception in thread "main" org.destinationsol.common.SolException: Something is trying to get a SolShip hero while the hero is in Transcendent state.
	at org.destinationsol.game.Hero.getShip(Hero.java:97)
	at org.destinationsol.ui.nui.screens.MainGameScreen.onItemsButtonClicked(MainGameScreen.java:260)
	at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
	at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
	at org.destinationsol.ui.nui.widgets.KeyActivatedButton.onKeyEvent(KeyActivatedButton.java:99)
	at org.destinationsol.ui.nui.NUIScreenLayer.onKeyEvent(NUIScreenLayer.java:133)
	at org.destinationsol.ui.nui.screens.MainGameScreen.onKeyEvent(MainGameScreen.java:188)
	at org.destinationsol.ui.nui.NUIManager.update(NUIManager.java:204)
	at org.destinationsol.SolApplication.update(SolApplication.java:254)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:231)
	at org.destinationsol.SolApplication.render(SolApplication.java:195)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:149)
```
