### ISSUE TITLE
Crash when approaching a planet

### ISSUE THREAD

**Issue by guiweber** [MovingBlocks/DestinationSol#553]
## What you were trying to do

Approaching a planet

### What actually happened

Game crashed to desktop

### How to reproduce

Could not reproduce. It happened once when I was nearing a planet.

### Log details and game version

V2.0.0 On steam

java.lang.NullPointerException
	at org.destinationsol.game.ObjectManager.recalcRadius(ObjectManager.java:159)
	at org.destinationsol.game.ObjectManager.addObjNow(ObjectManager.java:200)
	at org.destinationsol.game.ObjectManager.addRemove(ObjectManager.java:183)
	at org.destinationsol.game.ObjectManager.update(ObjectManager.java:145)
	at org.destinationsol.game.SolGame.lambda$update$2(SolGame.java:317)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.destinationsol.game.SolGame.lambda$update$3(SolGame.java:316)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.destinationsol.game.SolGame.update(SolGame.java:315)
	at org.destinationsol.SolApplication.update(SolApplication.java:235)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:210)
	at org.destinationsol.SolApplication.render(SolApplication.java:174)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:149)

**Comment by Cervator** [comment]
Thanks for the report @guiweber ! Especially appreciate the stacktrace, that might give us a place for adding some better error handling to figure out which condition can cause that.
