### ISSUE TITLE
Respawn crashed

### ISSUE THREAD

**Issue by kanewinter** [MovingBlocks/DestinationSol#580]
https://drive.google.com/uc?id=1gUwLWecQFqy_-Br6iuOzGSUx0E6tKDNq&export=download

**Comment by Cervator** [comment]
Hi there - that log file doesn't really contain a lot of stuff. Could you please let us know what version of the game you were playing?

**Comment by BenjaminAmos** [comment]
This crash has the same stacktrace as #553, so both issues may have the same underlying cause.

**Comment by BenjaminAmos** [comment]
I don't know if that file sharing link will last forever, so I'm copying in the contents here to prevent it from getting lost.
```text
USER-GIVEN INFO:
respawning

ERROR STACK TRACE:
java.lang.NullPointerException
	at org.destinationsol.game.ObjectManager.recalcRadius(ObjectManager.java:159)
	at org.destinationsol.game.ObjectManager.addObjNow(ObjectManager.java:200)
	at org.destinationsol.game.ObjectManager.addRemove(ObjectManager.java:183)
	at org.destinationsol.game.ObjectManager.update(ObjectManager.java:145)
	at org.destinationsol.game.SolGame.lambda$update$2(SolGame.java:317)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.destinationsol.game.SolGame.lambda$update$3(SolGame.java:316)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.destinationsol.game.SolGame.update(SolGame.java:315)
	at org.destinationsol.SolApplication.update(SolApplication.java:235)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:210)
	at org.destinationsol.SolApplication.render(SolApplication.java:174)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:149)
```
