### ISSUE TITLE
Tutorial Waypoint crash

### ISSUE THREAD

**Issue by DerekMuenzel** [MovingBlocks/DestinationSol#690]
### What you were trying to do
Go through tutorial.
### What actually happened
Crashed game.
### How to reproduce

* Play tutorial
* Get to point of tutorial where you create a way point in the map.
* Create way point.
* Delete way point before leaving map.
* Leave map without any way points created.
* Crash game.

### Log details and game version
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.destinationsol.game.tutorial.steps.FlyToHeroFirstWaypointStep.start(FlyToHeroFirstWaypointStep.java:39)
	at org.destinationsol.game.tutorial.TutorialManager.update(TutorialManager.java:309)
	at org.destinationsol.game.SolGame.lambda$update$2(SolGame.java:394)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.destinationsol.game.SolGame.lambda$update$3(SolGame.java:393)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.destinationsol.game.SolGame.update(SolGame.java:392)
	at org.destinationsol.SolApplication.update(SolApplication.java:267)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:241)
	at org.destinationsol.SolApplication.render(SolApplication.java:205)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:138)

**Comment by BenjaminAmos** [comment]
Thanks for reporting this! I've prepared a fix in #691 but it may be a bit longer before I get round to applying it.
